export const actionKey: Record<string, string> = {
  'typeFields.size': 'Size',
  'typeFields.floor': 'Floor',
  'typeFields.floorCount': 'Floor count',
  'typeFields.bathroomCount': 'Bathroom count',
  'typeFields.bedroomCount': 'Bedroom count',
  'typeFields.unitNumber': 'Unit number',
  'typeFields.roomCount': 'Rooms',
  price: 'Price',
  category: 'Category',
  descriptionRU: 'Description, RU',
  descriptionEN: 'Description, EN',
  'typeFields.hasMaidRoom': "Maid's",
  propertyAmenity: 'Amenities',
  'typeFields.furnishing': 'Furnishing type',
  'typeFields.parkingSpacesCount': 'No of parking spaces',
  views: 'A view of',
  publications: 'Object published on',
  buildingId: 'Building',
  status: 'Status',
  'typeFields.title': 'Title',
  'typeFields.hasBalcony': 'Balcony',
  isDraft: 'Created',
  currencyId: 'Currency',
  districtId: 'District',
  Photo: 'Photo',
  'typeFields.titleDeed': 'Title deed',
  'typeFields.financialStatus': 'Financial status',
  'typeFields.furnishingType': 'Furnishing type',
  'typeFields.plotSize': 'Plot size',
  'typeFields.propertyType': 'Property type',
};
