export enum Action {
  TOGGLE_TRANSACTION = 'TOGGLE_TRANSACTION',
  TOGGLE_PROPERTY_TYPE = 'TOGGLE_PROPERTY_TYPE',
  TOGGLE_BUILDING_TYPE = 'TOGGLE_BUILDING_TYPE',
  TOGGLE_HISTORY_TYPE = 'TOGGLE_HISTORY_TYPE',
}
