export enum ActionTypes {
  PROPERTY_UPDATED = 'PROPERTY_UPDATED',
  SHOW_REQUESTED = 'SHOW_REQUESTED',
  PRICE_CHANGED = 'PRICE_CHANGED',
  RESPONSIBLE_CHANGED = 'RESPONSIBLE_CHANGED',
  PUBLICATION_STATUS = 'PUBLICATION_STATUS',
  PUBLICATION_REQUESTED = 'PUBLICATION_REQUESTED',
  STATUS_CHANGED = 'STATUS_CHANGED',
}
