export enum PropertyType {
  APARTMENT = 'APARTMENT',
  TOWNHOUSE = 'TOWNHOUSE',
  VILLA = 'VILLA',
  BUNGALOW = 'BUNGALOW',
  COMPOUND = 'COMPOUND',
  DUPLEX = 'DUPLEX',
  HALF_FLOOR = 'HALF_FLOOR',
  FULL_FLOOR = 'FULL_FLOOR',
  PENTHOUSE = 'PENTHOUSE',
  WHOLE_BUILDING = 'WHOLE_BUILDING',
  BULK_UNITS = 'BULK_UNITS',
  LAND = 'LAND',
}
