export enum Punctuation {
  PERIOD = '.',
  COMMA = ',',
  QUESTION_MARK = '?',
  EXCLAMATION_MARK = '!',
  COLON = ':',
  SEMICOLON = ';',
  DASH = '-',
  HYPHEN = '—',
  PARENTHESES_OPEN = '(',
  PARENTHESES_CLOSE = ')',
  BRACKETS_OPEN = '[',
  BRACKETS_CLOSE = ']',
  BRACE_OPEN = '{',
  BRACE_CLOSE = '}',
  QUOTATION_MARK = '"',
  APOSTROPHE = "'",
  SLASH = '/',
  BACKSLASH = '\\',
  UNDERSCORE = '_',
}
